openapi: 3.0.0
info:
  title: ARGENT BANK
  description: |-
    ARGENT BANK is a bank application.  
    For the moment, only the user part of the api is documented and managed.  
    In the future we will have the transaction part.
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: User
  - name: Transaction
paths:
  /user/login:
    post:
      tags:
        - User
      summary: Sign in (to get token)
      description: >
        Authenticate a user by email and password.  
        Returns a JWT token if login is successful.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                email: tony@stark.com
                password: password123
      responses:
        '200':
          description: User successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: User successfully logged in
                  body:
                    type: object
                    properties:
                      token:
                        type: string
                        example: token
  /user/profile:
    post:
      tags:
        - User
      summary: Get user profile (with token)
      description: >
        Retrieve the authenticated user's profile.  
        Requires a valid JWT token in the `Authorization` header.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved user profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Successfully got user profile data
                  body:
                    type: object
                    properties:
                      email:
                        type: string
                        example: tony@stark.com
                      firstName:
                        type: string
                        example: Tony
                      lastName:
                        type: string
                        example: Stark
                      createdAt:
                        type: string
                        format: date-time
                        example: 2025-07-24T12:58:48.485Z
                      updatedAt:
                        type: string
                        format: date-time
                        example: 2025-09-04T15:06:41.975Z
                      id:
                        type: string
                        example: 68822e08ce3e08259cf4f30b

    put:
      tags:
        - User
      summary: Change userName (with Token)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstName: John
                lastName: Doe
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}